version: "3.9"

services:
  kafka:
    restart: always
    container_name: kafka
    image: apache/kafka-native:3.8.0
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9092"]
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_NODE_ID: 1
      CLUSTER_ID: "iQsUL1SRTUbIdzWbBMmhVg=="
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
    networks:
      - tsm
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - tsm
    command: --logging.level.zipkin2=TRACE

  event-management-service:
    image: nabeelbhatti/event-management-service
    container_name: ems
    ports:
      - "9090:9090"
    healthcheck:
      test: "curl --fail --silent localhost:9090/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - tsm
    depends_on:
      kafka:
        condition: service_healthy
    links:
      - zipkin
    restart: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:29092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans


  notification-service:
    image: nabeelbhatti/notifications-service
    container_name: notifications-service
    ports:
      - "9094:9094"
    networks:
      - tsm
    depends_on:
      kafka:
        condition: service_healthy
    links:
      - eureka
    restart: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:29092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans



  account-service:
    image: nabeelbhatti/account-management-service
    container_name: account-service
    ports:
      - "9095:9095"
    networks:
      - tsm
    depends_on:
      kafka:
        condition: service_healthy
    restart: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:29092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans


  gatway-service:
    image: nabeelbhatti/gateway
    container_name: booking-service
    ports:
      - "8080:8080"
    networks:
      - tsm
    depends_on:
      kafka:
        condition: service_healthy
    restart: always
    environment:
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://localhost:9090
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: event-management
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path= /jio/*
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]: StripPrefix=1
#      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://airtel-microservice:9502
#      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: airtel-service
#      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path= /airtel/*
#      SPRING_CLOUD_GATEWAY_ROUTES[1]_FILTERS[0]: StripPrefix=1
#      SPRING_CLOUD_GATEWAY_ROUTES[2]_URI: http://vodaphone-microservice:9503
#      SPRING_CLOUD_GATEWAY_ROUTES[2]_ID: vodaphone-service
#      SPRING_CLOUD_GATEWAY_ROUTES[2]_PREDICATES[0]: Path= /vodaphone/*
#      SPRING_CLOUD_GATEWAY_ROUTES[2]_FILTERS[0]: StripPrefix=1
  booking-service:
    image: nabeelbhatti/event-booking-service
    container_name: booking-service
    ports:
      - "9091:9091"
    networks:
      - tsm
    depends_on:
      kafka:
        condition: service_healthy
    restart: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:29092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans


networks:
  tsm:
    driver: bridge
    name: tsm
