spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: event-management
          uri: http://localhost:9090
          predicates:
            - Path=/rakbank/event-management-service/**
        - id: booking-management
          uri: http://localhost:9091
          predicates:
            - Path=/rakbank/event-booking-service/**
        - id: payment-service
          uri: http://localhost:9093
          predicates:
            - Path=/rakbank/event-payment-service/**
        - id: account-management-service
          uri: http://localhost:9095
          predicates:
            - Path=/rakbank/account-management-service/**
        - id: notifications-service
          uri: http://localhost:9094
          predicates:
            - Path=/rakbank/notifications-service/**
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework: info
    org.hibernate: debug

# Server configuration
server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always



# Monitoring
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
